#Bitmex:
#  api_key: Hi7WUgzxyzCRY_1BJ0e7meab
#  api_secret: A64KwkbRqURgFAmarfF758ceAVtFoIJWZIXe5lpRIeld1FxD
#  pairs:
#    "BTC/USD": "XBTUSD"
#    "ETH/USD": "ETHUSD"
#    "SOL/USD": "SOLUSD"
#    "DOGE/USD": "DOGEUSD"
#    "ADA/USD": "ADAUSD"
#    "XRP/USD": "XRPUSD"

Coinbase:
  api_key: organizations/3a515644-f82d-412e-956e-38ee985c06d4/apiKeys/4b4bca01-ec6c-49b5-ad98-c427a6a80a78
  api_secret: -----BEGIN EC PRIVATE KEY-----\nMHcCAQEEILioy4fqfPSC8p2Z2OhdxJo+rw3X5yNON+dutYXPNMgBoAoGCCqGSM49\nAwEHoUQDQgAEGFpwjI3Bs7ePdVjsOOsQs77dZZc1acrlgFkX69KJFslavy/6qlQM\nFRTUDrQeeyF1Xyjc1VhVLdOJUjlsosvXFA==\n-----END EC PRIVATE KEY-----\n
  pairs:
    "BTC/USD": "BTC/USD"
    "ETH/USD": "ETH/USD"
    "SOL/USD": "SOL/USD"
    "DOGE/USD": "DOGE/USD"
    "ADA/USD": "ADA/USD"
    "XRP/USD": "XRP/USD"

#Binance

#HTX:
#  api_key: 924d44f9-ez2xc4vb6n-0b47dc63-4eaa3
#  api_secret: db4499ce-2b99a0db-bd1437c4-e9b93
#  pairs:
#    "BTC/USD": "BTC/USDT"
#    "ETH/USD": "ETH/USDT"
#    "SOL/USD": "SOL/USDT"
#    "DOGE/USD": "DOGE/USDT"
#    "ADA/USD": "ADA/USDT"
#    "XRP/USD": "XRP/USDT"
#
#Kraken:
#  api_key: sJK+rjNp1UA9IQwZDalwg+usU9LTG5KTmxt6Kl92++4vk4/+jMcIQYyZ
#  api_secret: 8Qevz6zp3JzOTwBEw/bv2+KsFCTZL5DiKeqVI0TuiZXfkzoy8jnM+TtB0Q7NoZtn3UYhCC/Yfau2Dlis4xLOdA==
#  pairs:
#    "BTC/USD": "BTC/USD"
#    "ETH/USD": "ETH/USD"
#    "SOL/USD": "SOL/USD"
#    "DOGE/USD": "DOGE/USD"
#    "ADA/USD": "ADA/USD"
#    "XRP/USD": "XRP/USD"