# Example exchange credential configuration.
# Copy this file to config/exchange_config.yaml and replace the placeholder values
# with your real API credentials before running the live trading scripts or
# building the Docker image. Never commit actual credentials to source control.

kraken_websocket:
  apiKey: YOUR_KRAKEN_API_KEY
  secret: YOUR_KRAKEN_API_SECRET
  # password: YOUR_KRAKEN_API_PASSWORD  # Optional; uncomment if your key requires it

bitmex:
  apiKey: YOUR_BITMEX_API_KEY
  secret: YOUR_BITMEX_API_SECRET

coinbase:
  apiKey: YOUR_COINBASE_API_KEY
  secret: YOUR_COINBASE_API_SECRET
  # passphrase: YOUR_COINBASE_API_PASSPHRASE
